services:
  db:
    build: 
      context: ./Docker/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"

  backend:
    build: 
      context: .
      dockerfile: Docker/backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/chatbot_db
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: 
      ACCESS_TOKEN_EXPIRE_HOURS: "24"
      SECRET_KEY: 
      ALGORITHM: "HS256"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5