services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/db-data:/var/lib/postgresql/data
   
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"